apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: lab4
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 256Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 1Gi
