---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-db-password
  namespace: default
spec:
  encryptedData:
    password: AgBJJpkoxYlBpbH0Rqp83Z7EqRt5CrreGLYFUEs5crqxzkgv+i8nffLDemn30Zxrv83gYZFFrK/pyXLt/adwb3ikdUK0xcxIRH65KV1TJhp1ci/OYqMEMFOhWqJviPCzjdXJDQ6rDv7y9pQlGcZ9HPH7+BtNwUGfrM6LlKeSKr51tgVuDruPQeXEvKBLYH/lvCRC2y61Qex5MZURQilWJfNjhna5Cfo1BuZnWQm/UBUaqXYAL8QMcPqI4PRpEhRiUrwrPt7ex2koaNga0ZZuHLOmGvO1R3JOPw9BF4TIQ9A8M0YM/ZVK7rPkCaWnNIfF9Z7s3vQE9sb+3Zxmknbo6xBC7rrcNxda8dvbxxcuNo63bN0EiQ9xWjwUhYzxDlPKufhOcOMMQ90MmX0xMbuypo1eBBD9owJ0P1bWpYAtmCCqip3pJd2NxpNhysq0ZR0ZpwIRoNufNHcP8tE7oA4XvwCFq1ZbqRZaKYMWMl47iKsFkE+boIsAR9VfPCBwj3GJDk7qRLn5hIZD1CFfTCm2ysBOdIkD2msuSXFn4htyV7aaiarQ5BDZWxN7aW0qUjFFRXUYQFblT7s+ycX3vqA60ZogUYrDzfrIi4ukj83DLlwumapvHcneTW+cARU0gaPQRRhLDSv1d3X/EY8f9E6ccpZOpFut893STvMjcijEzq1/jEi9IYDnwvDyWvyFDPG+A47qyos+sdqRD5odbBe2CQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-db-password
      namespace: default
