---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-db-password
  namespace: default
spec:
  encryptedData:
    password: AgBH00k0U9qoCxxvG1qvo03A1jFyVsCv5cx9qw2EeH35CsuEsa7+ZkEMEZ04P0lSzIWYL7gN9CNB8hz8x4472XfYwXcWjrwlH5DUNjbL0t9kzvbGZADmIGK9LS8npWqlfROjFcjt3tsXjUjZ+sOfMvwPMpxQOkqFO+np1/K3hRin7YcRUHsmaxedu7KCvDuncvhJYb0VQrE+GTtdJezRSPtZZQI5bsEQGrw7H/MFwQnD93q2T/5d6Sb/cxoY8sryuKs2mSFO9PuvVmvlFLSWiTtbkhLcISfZWUG1b65ioXcwrPLucWOphiekUXsgiWlSQQH4WYqaHOyOVSvccm2X0WHS8kX7pKgytwiGrAv/YqjOv7EJbgmdMqGdr3Fj4b9T218UKY8TtCmUV2/JSq+ZCv0L3t8ZQwrL53g1BmLh4spVZLWLIsreIlGstDEFQtVgyq9hAQNL/MOGKwACp6+8Tw/MKttBjwb/hzR1eD921Hpx4TOuGwqye2TgGeAIyZ5KEhHqLq+vME1uop2Y+h98yF7xGwXO7QRhW+++aM8wVOw08J1KqNp10e+QOghHT3+wK/KqsVuYCe1BgQ7mwJdPNDbTkDbP0A4K3mvfYQ77XCDxvBeST6ysFzuyl8uj4yi8nu5CKPpojqYC9WvRL3Gm3Ov2itqiy+f1zrPaXv2FXHY4zZKYrjWA6Xq8ONlxCbi6uzathRU1BSsU0OiNPxqK3Q==
  template:
    metadata:
      creationTimestamp: null
      name: my-db-password
      namespace: default
